import { Inter } from 'next/font/google'
import Section from '../sections/form';
import Head from 'next/head';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <>
          <title>GPT Sentence Generator</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <Script src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8886377477645608' crossOrigin='anonymous'/>
        </>
      </Head>
      <main>
        <Section
          title="Pratique Inglês de graça Criando Frases Com Nossa AI"
          subTitle="Conheça nosso formulário conectado com nossa Inteligência Artificial. Nele você pode decidir qual tipo de frase você quer (pergunta, negação, afirmação ou pergunta negando). Com o clique do botão 'Gerar' nossa inteligência artifiical vai gerar uma frase para você. No campo de texto em baixo, transforme em inglês a frase. Dependendo de sua resposta, nossa AI também vai dizer se você errou ou não ao apertar no botão 'Resultado'. 'Reinicie' caso queira reiniciar e criar uma frase nova. Com a prática você ficará um especialista em criar frases em inglês."
          titleCard="Escolha os tipos de frases que quer treinar abaixo"
        />
      </main>
    </>
  )
}

/*

//
  <Fema data={data} />
  export async function getServerSideProps () {

  const res = await fetch("https://data.cdc.gov/resource/8pt5-q6wp.json");
  const data = await res.json();

  return {

      props: {
        data,
      },

  };

}*/