import { Inter } from 'next/font/google'
import Section from '../sections/form';
import Head from 'next/head';
import Script from 'next/script';
import Idea from '../components/Content/idea'
import { Provider } from 'react-redux';
import reducer from '@/redux/reducer';
import { updateGptSentence } from '@/redux/reducer';
import {combineReducers, configureStore } from '@reduxjs/toolkit';
import { updateGptCorrection } from '@/redux/reducer';
import { H4Text, PText } from '@/components/Items/Texts/texts';
import { Frame } from '@/components/Layout/layout';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const rootReducer = combineReducers({
    reducer,
    updateGptSentence,
    updateGptCorrection,
  })

  const store = configureStore({
    reducer: rootReducer,
  })

  return (
    <>

      <Provider store={store}>
        <Head>
          <>
            <title>GPT Sentence Generator</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </>
        </Head>
        <main>
          <Section
            title="Pratique Inglês de graça Criando Frases Com Nossa AI"
            subTitle="Conheça nosso formulário conectado com nossa Inteligência Artificial. Nele você pode decidir qual tipo de frase você quer (pergunta, negação, afirmação ou pergunta negando). Com o clique do botão 'Gerar' nossa inteligência artifiical vai gerar uma frase para você. No campo de texto em baixo, transforme em inglês a frase. Dependendo de sua resposta, nossa AI também vai dizer se você errou ou não ao apertar no botão 'Resultado'. 'Reinicie' caso queira reiniciar e criar uma frase nova. Com a prática você ficará um especialista em criar frases em inglês."
            titleCard="Escolha os tipos de frases que quer treinar abaixo"
          />
        </main>
      </Provider>
    </>
  )
}